#!/usr/bin/env bash

homeDir="$HOME";
processIdFilename=".wf-recorder-process-id";
outputFilename="record.mp4";

processIdFilepath="$homeDir/$processIdFilename";
outputFilepath="$homeDir/$outputFilename";

startRecording() {
  wf-recorder -g "$(slurp)" -f "$outputFilepath" -y 2> /dev/null&

  echo "$!" > "$processIdFilepath";
}

stopRecording() {
  local pid;
  pid="$(cat "$processIdFilepath")";
  
  kill "$pid";
  rm "$processIdFilepath";

  notify-send "Screen recorder" "Record saved at $outputFilepath";
}

if [[ ! -f "$processIdFilepath" ]]; then
  startRecording;
else
  stopRecording;
fi

